export interface Surah {
  number: number;
  name: string;
  englishName: string;
  ayahsCount: number;
}

export const surahs: Surah[] = [
  { number: 1, name: "الفاتحة", englishName: "Al-Fatiha", ayahsCount: 7 },
  { number: 2, name: "البقرة", englishName: "Al-Baqarah", ayahsCount: 286 },
  { number: 3, name: "آل عمران", englishName: "Aal-Imran", ayahsCount: 200 },
  { number: 4, name: "النساء", englishName: "An-Nisa", ayahsCount: 176 },
  { number: 5, name: "المائدة", englishName: "Al-Ma'idah", ayahsCount: 120 },
  { number: 6, name: "الأنعام", englishName: "Al-An'am", ayahsCount: 165 },
  { number: 7, name: "الأعراف", englishName: "Al-A'raf", ayahsCount: 206 },
  { number: 8, name: "الأنفال", englishName: "Al-Anfal", ayahsCount: 75 },
  { number: 9, name: "التوبة", englishName: "At-Tawbah", ayahsCount: 129 },
  { number: 10, name: "يونس", englishName: "Yunus", ayahsCount: 109 },
  { number: 11, name: "هود", englishName: "Hud", ayahsCount: 123 },
  { number: 12, name: "يوسف", englishName: "Yusuf", ayahsCount: 111 },
  { number: 13, name: "الرعد", englishName: "Ar-Ra'd", ayahsCount: 43 },
  { number: 14, name: "إبراهيم", englishName: "Ibrahim", ayahsCount: 52 },
  { number: 15, name: "الحجر", englishName: "Al-Hijr", ayahsCount: 99 },
  { number: 16, name: "النحل", englishName: "An-Nahl", ayahsCount: 128 },
  { number: 17, name: "الإسراء", englishName: "Al-Isra", ayahsCount: 111 },
  { number: 18, name: "الكهف", englishName: "Al-Kahf", ayahsCount: 110 },
  { number: 19, name: "مريم", englishName: "Maryam", ayahsCount: 98 },
  { number: 20, name: "طه", englishName: "Ta-Ha", ayahsCount: 135 },
  { number: 21, name: "الأنبياء", englishName: "Al-Anbiya", ayahsCount: 112 },
  { number: 22, name: "الحج", englishName: "Al-Hajj", ayahsCount: 78 },
  { number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", ayahsCount: 118 },
  { number: 24, name: "النور", englishName: "An-Nur", ayahsCount: 64 },
  { number: 25, name: "الفرقان", englishName: "Al-Furqan", ayahsCount: 77 },
  { number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", ayahsCount: 227 },
  { number: 27, name: "النمل", englishName: "An-Naml", ayahsCount: 93 },
  { number: 28, name: "القصص", englishName: "Al-Qasas", ayahsCount: 88 },
  { number: 29, name: "العنكبوت", englishName: "Al-Ankabut", ayahsCount: 69 },
  { number: 30, name: "الروم", englishName: "Ar-Rum", ayahsCount: 60 },
  { number: 31, name: "لقمان", englishName: "Luqman", ayahsCount: 34 },
  { number: 32, name: "السجدة", englishName: "As-Sajdah", ayahsCount: 30 },
  { number: 33, name: "الأحزاب", englishName: "Al-Ahzab", ayahsCount: 73 },
  { number: 34, name: "سبأ", englishName: "Saba", ayahsCount: 54 },
  { number: 35, name: "فاطر", englishName: "Fatir", ayahsCount: 45 },
  { number: 36, name: "يس", englishName: "Ya-Sin", ayahsCount: 83 },
  { number: 37, name: "الصافات", englishName: "As-Saffat", ayahsCount: 182 },
  { number: 38, name: "ص", englishName: "Sad", ayahsCount: 88 },
  { number: 39, name: "الزمر", englishName: "Az-Zumar", ayahsCount: 75 },
  { number: 40, name: "غافر", englishName: "Ghafir", ayahsCount: 85 },
  { number: 41, name: "فصلت", englishName: "Fussilat", ayahsCount: 54 },
  { number: 42, name: "الشورى", englishName: "Ash-Shura", ayahsCount: 53 },
  { number: 43, name: "الزخرف", englishName: "Az-Zukhruf", ayahsCount: 89 },
  { number: 44, name: "الدخان", englishName: "Ad-Dukhan", ayahsCount: 59 },
  { number: 45, name: "الجاثية", englishName: "Al-Jathiyah", ayahsCount: 37 },
  { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", ayahsCount: 35 },
  { number: 47, name: "محمد", englishName: "Muhammad", ayahsCount: 38 },
  { number: 48, name: "الفتح", englishName: "Al-Fath", ayahsCount: 29 },
  { number: 49, name: "الحجرات", englishName: "Al-Hujurat", ayahsCount: 18 },
  { number: 50, name: "ق", englishName: "Qaf", ayahsCount: 45 },
  { number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", ayahsCount: 60 },
  { number: 52, name: "الطور", englishName: "At-Tur", ayahsCount: 49 },
  { number: 53, name: "النجم", englishName: "An-Najm", ayahsCount: 62 },
  { number: 54, name: "القمر", englishName: "Al-Qamar", ayahsCount: 55 },
  { number: 55, name: "الرحمن", englishName: "Ar-Rahman", ayahsCount: 78 },
  { number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", ayahsCount: 96 },
  { number: 57, name: "الحديد", englishName: "Al-Hadid", ayahsCount: 29 },
  { number: 58, name: "المجادلة", englishName: "Al-Mujadilah", ayahsCount: 22 },
  { number: 59, name: "الحشر", englishName: "Al-Hashr", ayahsCount: 24 },
  { number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", ayahsCount: 13 },
  { number: 61, name: "الصف", englishName: "As-Saf", ayahsCount: 14 },
  { number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", ayahsCount: 11 },
  { number: 63, name: "المنافقون", englishName: "Al-Munafiqun", ayahsCount: 11 },
  { number: 64, name: "التغابن", englishName: "At-Taghabun", ayahsCount: 18 },
  { number: 65, name: "الطلاق", englishName: "At-Talaq", ayahsCount: 12 },
  { number: 66, name: "التحريم", englishName: "At-Tahrim", ayahsCount: 12 },
  { number: 67, name: "الملك", englishName: "Al-Mulk", ayahsCount: 30 },
  { number: 68, name: "القلم", englishName: "Al-Qalam", ayahsCount: 52 },
  { number: 69, name: "الحاقة", englishName: "Al-Haqqah", ayahsCount: 52 },
  { number: 70, name: "المعارج", englishName: "Al-Ma'arij", ayahsCount: 44 },
  { number: 71, name: "نوح", englishName: "Nuh", ayahsCount: 28 },
  { number: 72, name: "الجن", englishName: "Al-Jinn", ayahsCount: 28 },
  { number: 73, name: "المزمل", englishName: "Al-Muzzammil", ayahsCount: 20 },
  { number: 74, name: "المدثر", englishName: "Al-Muddaththir", ayahsCount: 56 },
  { number: 75, name: "القيامة", englishName: "Al-Qiyamah", ayahsCount: 40 },
  { number: 76, name: "الإنسان", englishName: "Al-Insan", ayahsCount: 31 },
  { number: 77, name: "المرسلات", englishName: "Al-Mursalat", ayahsCount: 50 },
  { number: 78, name: "النبأ", englishName: "An-Naba", ayahsCount: 40 },
  { number: 79, name: "النازعات", englishName: "An-Nazi'at", ayahsCount: 46 },
  { number: 80, name: "عبس", englishName: "Abasa", ayahsCount: 42 },
  { number: 81, name: "التكوير", englishName: "At-Takwir", ayahsCount: 29 },
  { number: 82, name: "الانفطار", englishName: "Al-Infitar", ayahsCount: 19 },
  { number: 83, name: "المطففين", englishName: "Al-Mutaffifin", ayahsCount: 36 },
  { number: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", ayahsCount: 25 },
  { number: 85, name: "البروج", englishName: "Al-Buruj", ayahsCount: 22 },
  { number: 86, name: "الطارق", englishName: "At-Tariq", ayahsCount: 17 },
  { number: 87, name: "الأعلى", englishName: "Al-A'la", ayahsCount: 19 },
  { number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", ayahsCount: 26 },
  { number: 89, name: "الفجر", englishName: "Al-Fajr", ayahsCount: 30 },
  { number: 90, name: "البلد", englishName: "Al-Balad", ayahsCount: 20 },
  { number: 91, name: "الشمس", englishName: "Ash-Shams", ayahsCount: 15 },
  { number: 92, name: "الليل", englishName: "Al-Layl", ayahsCount: 21 },
  { number: 93, name: "الضحى", englishName: "Ad-Duha", ayahsCount: 11 },
  { number: 94, name: "الشرح", englishName: "Ash-Sharh", ayahsCount: 8 },
  { number: 95, name: "التين", englishName: "At-Tin", ayahsCount: 8 },
  { number: 96, name: "العلق", englishName: "Al-Alaq", ayahsCount: 19 },
  { number: 97, name: "القدر", englishName: "Al-Qadr", ayahsCount: 5 },
  { number: 98, name: "البينة", englishName: "Al-Bayyinah", ayahsCount: 8 },
  { number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", ayahsCount: 8 },
  { number: 100, name: "العاديات", englishName: "Al-Adiyat", ayahsCount: 11 },
  { number: 101, name: "القارعة", englishName: "Al-Qari'ah", ayahsCount: 11 },
  { number: 102, name: "التكاثر", englishName: "At-Takathur", ayahsCount: 8 },
  { number: 103, name: "العصر", englishName: "Al-Asr", ayahsCount: 3 },
  { number: 104, name: "الهمزة", englishName: "Al-Humazah", ayahsCount: 9 },
  { number: 105, name: "الفيل", englishName: "Al-Fil", ayahsCount: 5 },
  { number: 106, name: "قريش", englishName: "Quraysh", ayahsCount: 4 },
  { number: 107, name: "الماعون", englishName: "Al-Ma'un", ayahsCount: 7 },
  { number: 108, name: "الكوثر", englishName: "Al-Kawthar", ayahsCount: 3 },
  { number: 109, name: "الكافرون", englishName: "Al-Kafirun", ayahsCount: 6 },
  { number: 110, name: "النصر", englishName: "An-Nasr", ayahsCount: 3 },
  { number: 111, name: "المسد", englishName: "Al-Masad", ayahsCount: 5 },
  { number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", ayahsCount: 4 },
  { number: 113, name: "الفلق", englishName: "Al-Falaq", ayahsCount: 5 },
  { number: 114, name: "الناس", englishName: "An-Nas", ayahsCount: 6 },
];

export interface Reciter {
  id: string;
  name: string;
  everyayahId: string;
}

export const reciters: Reciter[] = [
  { id: "ar.alafasy", name: "مشاري راشد العفاسي", everyayahId: "Alafasy_128kbps" },
  { id: "ar.abdulbasitmurattal", name: "عبد الباسط عبد الصمد (مرتل)", everyayahId: "Abdul_Basit_Murattal_192kbps" },
  { id: "ar.abdulsamad", name: "عبد الباسط عبد الصمد (مجود)", everyayahId: "Abdul_Basit_Mujawwad_192kbps" },
  { id: "ar.abdullahbasfar", name: "عبد الله بصفر", everyayahId: "Abdullah_Basfar_192kbps" },
  { id: "ar.abdurrahmaansudais", name: "عبد الرحمن السديس", everyayahId: "Abdurrahmaan_As-Sudais_192kbps" },
  { id: "ar.shuraim", name: "سعود الشريم", everyayahId: "Shuraim_128kbps" },
  { id: "ar.hudhaify", name: "علي الحذيفي", everyayahId: "Al-Hudhaify_128kbps" },
  { id: "ar.husary", name: "محمود خليل الحصري", everyayahId: "Husary_128kbps" },
  { id: "ar.minshawi", name: "محمد صديق المنشاوي (مرتل)", everyayahId: "Minshawy_Murattal_128kbps" },
  { id: "ar.minshawimujawwad", name: "محمد صديق المنشاوي (مجود)", everyayahId: "Minshawy_Mujawwad_192kbps" },
  { id: "ar.muhammadayyoub", name: "محمد أيوب", everyayahId: "Muhammad_Ayyoub_128kbps" },
  { id: "ar.muhammadjibreel", name: "محمد جبريل", everyayahId: "Muhammad_Jibreel_128kbps" },
  { id: "ar.shaatree", name: "أبو بكر الشاطري", everyayahId: "Abu-Bakr_Ash-Shaatree_128kbps" },
  { id: "ar.ahmedajamy", name: "أحمد بن علي العجمي", everyayahId: "Ahmed_ibn_Ali_al-Ajamy_128kbps" },
  { id: "ar.mahermuaiqly", name: "ماهر المعيقلي", everyayahId: "Maher_AlMuaiqly_128kbps" },
  { id: "ar.saaborim", name: "صابر عبد الحكم", everyayahId: "Saaborim_128kbps" },
  { id: "ar.yasser", name: "ياسر الدوسري", everyayahId: "Yasser_Ad-Dussary_128kbps" },
  { id: "ar.nabil", name: "نبيل الرفاعي", everyayahId: "Nabil_Ar-Rifai_128kbps" },
  { id: "ar.husaryteaching", name: "الحصري (المعلم)", everyayahId: "Husary_Teaching_128kbps" },
];

export interface VideoPreset {
  id: string;
  name: string;
  width: number;
  height: number;
  platforms: string;
}

export const videoPresets: VideoPreset[] = [
  { id: "youtube", name: "YouTube", width: 1920, height: 1080, platforms: "16:9 - يوتيوب، فيسبوك" },
  { id: "instagram-post", name: "Instagram Post", width: 1080, height: 1080, platforms: "1:1 - انستغرام" },
  { id: "instagram-portrait", name: "Instagram Portrait", width: 1080, height: 1350, platforms: "4:5 - انستغرام بورتريه" },
  { id: "stories-reels", name: "Stories/Reels", width: 1080, height: 1920, platforms: "9:16 - ستوري، ريلز، تيك توك، شورتس" },
  { id: "tiktok", name: "TikTok", width: 1080, height: 1920, platforms: "9:16 - تيك توك" },
  { id: "twitter", name: "Twitter/X", width: 1280, height: 720, platforms: "16:9 - تويتر" },
  { id: "facebook-cover", name: "Facebook Video", width: 1280, height: 720, platforms: "16:9 - فيسبوك" },
  { id: "custom", name: "مقاس مخصص", width: 1920, height: 1080, platforms: "مخصص" },
];

import type { VideoSettings } from './types';

export const defaultSettings: VideoSettings = {
  surahNumber: null,
  ayahFrom: 1,
  ayahTo: 1,
  reciterId: 'ar.alafasy',
  videoPresetId: 'stories-reels',
  customWidth: 1080,
  customHeight: 1920,
  backgrounds: [],
  enableFade: true,
  fadeDuration: 1000,
  textPosition: 'center',
  textColor: '#ffffff',
  fontSize: 48,
  fontFamily: 'Amiri',
  showWatermark: false,
  watermarkText: '',
  quality: '1080p',
};

export const quranApiBase = "https://api.alquran.cloud/v1";
